import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { parse as parseYaml } from "yaml";
import constants from "../constants.json" with { type: "json" };

const { schemaVersion } = constants;
const originalSchemaDir = "schema";
const typedSchemaParentDir = "src/models";
const jsonSchemaDir = `docs/schema/v${schemaVersion}`;
const modelTypeNames = ["class-model"];

/**
 * Generates TypeScript schema file content with `as const` assertion.
 */
function generateTypeScriptSchema(schemaObject: unknown, name: string): string {
	return `
// Generated from ${originalSchemaDir}/${name}.yaml
// Do not edit manually - this file is automatically generated

/**
 * Schema object for model type: \`${name}\`
 */
export const schema = ${JSON.stringify(schemaObject, null, 2)} as const;
`.trimStart();
}

/**
 * Updates schema version references in YAML file and writes back if changed.
 * @returns The updated content (whether changed or not)
 */
function updateSchemaVersion(yamlFile: string): string {
	const yamlContent = readFileSync(yamlFile, "utf-8");
	let wasChanged = false;

	const updatedContent = yamlContent.replace(
		/conceptual-model\/schema\/v([^/]+)\//g,
		(_match, oldVersion) => {
			if (oldVersion === schemaVersion) {
				console.log(`Processing schema version: v${schemaVersion}`);
			} else {
				console.log(`Updating YAML ${yamlFile}: v${oldVersion} → v${schemaVersion}`);
				wasChanged = true;
			}
			return `conceptual-model/schema/v${schemaVersion}/`;
		},
	);

	if (wasChanged) {
		writeFileSync(yamlFile, updatedContent, "utf-8");
	}

	return updatedContent;
}

/**
 * Converts and saves TypeScript and JSON schema files from the original schema object.
 *
 * @param name Name of the schema to generate files for
 * @param schemaObject The originally-defined schema object
 */
function buildSchema(name: string, schemaObject: unknown): void {
	// Generate TypeScript schema file
	const typedSchemaDir = `${typedSchemaParentDir}/${name}`;
	mkdirSync(typedSchemaDir, { recursive: true });
	const tsFile = `${typedSchemaDir}/schema-object.ts`;
	const tsContent = generateTypeScriptSchema(schemaObject, name);
	writeFileSync(tsFile, tsContent, "utf-8");
	console.log(`Generated TypeScript schema: ${tsFile}`);

	// Generate JSON schema file
	const jsonFile = `${jsonSchemaDir}/${name}.json`;
	const jsonContent = JSON.stringify(schemaObject, null, "\t");
	writeFileSync(jsonFile, jsonContent, "utf-8");
	console.log(`Generated JSON schema: ${jsonFile}`);
}

/**
 * Builds the schema files by reading the original YAML files.
 * Also updates the schema version in the YAML files if necessary.
 */
function main(): void {
	mkdirSync(jsonSchemaDir, { recursive: true });

	for (const name of modelTypeNames) {
		console.group(`Processing schema for model type: ${name}`);

		const yamlFile = `${originalSchemaDir}/${name}.yaml`;
		const updatedContent = updateSchemaVersion(yamlFile);
		const schemaObject = parseYaml(updatedContent);
		buildSchema(name, schemaObject);

		console.groupEnd();
	}
}

main();
