import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { parse as parseYaml } from "yaml";
import constants from "../constants.json" with { type: "json" };

const { schemaVersions } = constants;

const originalSchemaDir = "schema";
const typedSchemaParentDir = "src/models";
const modelTypeNames: readonly ModelTypeName[] = ["class-model"];

type ModelTypeName = keyof typeof schemaVersions;

/**
 * Generates TypeScript schema file content with `as const` assertion.
 */
function generateTypeScriptSchema(schemaObject: unknown, name: ModelTypeName): string {
	return `
// Generated from ${originalSchemaDir}/${name}.yaml
// Do not edit manually - this file is automatically generated

/**
 * Schema object for model type: \`${name}\`
 */
export const schema = ${JSON.stringify(schemaObject, null, 2)} as const;
`.trimStart();
}

/**
 * Updates schema version references in YAML file and writes back if changed.
 * @returns The updated content (whether changed or not)
 */
function updateSchemaVersion(name: ModelTypeName, yamlFile: string): string {
	const yamlContent = readFileSync(yamlFile, "utf-8");
	const currentVersion = schemaVersions[name];
	let wasChanged = false;

	const updatedContent = yamlContent.replace(
		new RegExp(`conceptual-model/${name}/v([^/]+)/`, "g"),
		(_match, oldVersion) => {
			if (oldVersion === currentVersion) {
				console.log(`Processing schema version: v${currentVersion}`);
			} else {
				console.log(`Updating YAML ${yamlFile}: v${oldVersion} → v${currentVersion}`);
				wasChanged = true;
			}
			return `conceptual-model/${name}/v${currentVersion}/`;
		},
	);

	if (wasChanged) {
		writeFileSync(yamlFile, updatedContent, "utf-8");
	}

	return updatedContent;
}

/**
 * Converts and saves TypeScript and JSON schema files from the original schema object.
 *
 * @param name Name of the schema to generate files for
 * @param schemaObject The originally-defined schema object
 */
function buildSchema(name: ModelTypeName, schemaObject: object): void {
	const version = schemaVersions[name];

	// Generate TypeScript schema file
	const typedSchemaDir = `${typedSchemaParentDir}/${name}`;
	mkdirSync(typedSchemaDir, { recursive: true });
	const tsFile = `${typedSchemaDir}/schema-object.ts`;
	const tsContent = generateTypeScriptSchema(schemaObject, name);
	writeFileSync(tsFile, tsContent, "utf-8");
	console.log(`Generated TypeScript schema: ${tsFile}`);

	// Generate JSON schema file
	const jsonSchemaDir = `docs/${name}/v${version}`;
	mkdirSync(jsonSchemaDir, { recursive: true });
	const jsonFile = `${jsonSchemaDir}/schema.json`;
	const jsonContent = JSON.stringify(schemaObject, null, "\t");
	writeFileSync(jsonFile, jsonContent, "utf-8");
	console.log(`Generated JSON schema: ${jsonFile}`);
}

/**
 * Builds the schema files by reading the original YAML files.
 * Also updates the schema version in the YAML files if necessary.
 */
function main(): void {
	for (const name of modelTypeNames) {
		console.group(`Processing schema for model type: ${name}`);

		const yamlFile = `${originalSchemaDir}/${name}.yaml`;
		const updatedContent = updateSchemaVersion(name, yamlFile);
		const schemaObject: unknown = parseYaml(updatedContent);
		if (typeof schemaObject !== "object" || schemaObject === null) {
			throw new Error(`Unexpected schema object type for ${name}: ${typeof schemaObject}`);
		}
		buildSchema(name, schemaObject);

		console.groupEnd();
	}
}

main();
