// Generated from schema/class-model.yaml
// Do not edit manually - this file is automatically generated

/**
 * Schema object for model type: `class-model`
 */
export const schema = {
	$schema: "http://json-schema.org/draft-07/schema#",
	$id: "https://fal-works.github.io/conceptual-model/class-model/v0.1/schema.json",
	title: "@fal-works/conceptual-model | Conceptual class model schema",
	type: "object",
	properties: {
		$schema: { title: "JSON schema URL", type: "string" },
		title: { title: "Model title", type: "string" },
		groups: {
			title: "Model groups",
			type: "object",
			additionalProperties: { $ref: "#/definitions/group" },
		},
		nodes: {
			title: "Model nodes",
			type: "object",
			additionalProperties: { $ref: "#/definitions/node" },
		},
		edges: { title: "Model edges", type: "array", items: { $ref: "#/definitions/edge" } },
		layout: { $ref: "#/definitions/layout" },
	},
	additionalProperties: true,
	definitions: {
		group: {
			title: "Model group",
			type: "object",
			properties: { nodes: { title: "Group nodes", type: "array", items: { type: "string" } } },
			required: ["nodes"],
			additionalProperties: false,
		},
		node: {
			title: "Model node",
			oneOf: [
				{
					type: "object",
					properties: {
						label: { title: "Node label", type: "string" },
						attributes: { title: "Node attributes", type: "array", items: { type: "string" } },
					},
					additionalProperties: false,
				},
				{ type: "null" },
			],
		},
		edge: {
			title: "Model edge",
			type: "object",
			additionalProperties: false,
			properties: {
				source: { title: "Source node", type: "string" },
				relation: { $ref: "#/definitions/relation" },
				label: { title: "Edge label", type: "string" },
				multiplicity: { $ref: "#/definitions/multiplicity" },
				target: { title: "Target node", type: "string" },
			},
			required: ["source", "target"],
		},
		relation: {
			title: "Relationship type",
			type: "string",
			enum: ["is-a", "is-composed-of", "aggregates", "refers-to", "to", "with"],
		},
		multiplicity: {
			title: "Multiplicity",
			type: "string",
			pattern:
				"^(0|1|\\*|[0-9]+)(\\.\\.(0|1|\\*|[0-9]+))?( *-> *(0|1|\\*|[0-9]+)(\\.\\.(0|1|\\*|[0-9]+))?)?$",
		},
		layout: {
			title: "Layout Preferences",
			type: "object",
			properties: {
				direction: { title: "Layout direction", type: "string", enum: ["TB", "BT", "LR", "RL"] },
			},
			additionalProperties: false,
		},
	},
} as const;
