// Generated from schema/class-model.yaml
// Do not edit manually - this file is automatically generated

/**
 * Schema object for model type: `class-model`
 */
export const schema = {
	$schema: "http://json-schema.org/draft-07/schema#",
	$id: "https://fal-works.github.io/conceptual-model/class-model/v0.1/schema.json",
	title: "@fal-works/conceptual-model JSON Schema for conceptual class models",
	type: "object",
	properties: {
		$schema: { type: "string" },
		title: { type: "string" },
		nodes: { type: "object", additionalProperties: { $ref: "#/definitions/node" } },
		edges: { type: "array", items: { $ref: "#/definitions/edge" } },
		layout: { $ref: "#/definitions/layout" },
	},
	additionalProperties: true,
	required: ["nodes"],
	definitions: {
		node: {
			type: "object",
			properties: {
				label: { type: "string" },
				attributes: { type: "array", items: { type: "string" } },
			},
			additionalProperties: false,
		},
		edge: {
			type: "object",
			additionalProperties: false,
			properties: {
				label: { type: "string" },
				source: { type: "string" },
				relation: { $ref: "#/definitions/relation" },
				multiplicity: { $ref: "#/definitions/multiplicity" },
				target: { type: "string" },
			},
			required: ["source", "target"],
		},
		relation: { type: "string", enum: ["is-composed-of", "aggregates", "links-to", "is-a"] },
		multiplicity: {
			type: "string",
			pattern:
				"^(0|1|\\*|[0-9]+)(\\.\\.(0|1|\\*|[0-9]+))?( *-> *(0|1|\\*|[0-9]+)(\\.\\.(0|1|\\*|[0-9]+))?)?$",
		},
		layout: {
			type: "object",
			properties: { direction: { type: "string", enum: ["TB", "BT", "LR", "RL"] } },
			additionalProperties: false,
		},
	},
} as const;
