// Generated from schema/class-model.yaml
// Do not edit manually - this file is automatically generated

import type { FromSchema } from "json-schema-to-ts";
import type { schema } from "./schema-object.ts";

/**
 * Represents a conceptual class model.
 *
 * The type is automatically generated from the JSON schema.
 */
export type ClassModel = FromSchema<typeof schema>;

/**
 * TypeScript type for a single group in the model.
 * Represents a group for organizing related nodes.
 */
export type ClassModelGroup = NonNullable<ClassModel["groups"]>[string];

/**
 * TypeScript type for a single node (class) in the model.
 * Represents a class, entity, or concept with optional attributes.
 */
export type ClassModelNode = NonNullable<ClassModel["nodes"]>[string];

/**
 * TypeScript type for a single edge (relationship) in the model.
 * Represents connections between classes like composition, inheritance, etc.
 */
export type ClassModelEdge = NonNullable<ClassModel["edges"]>[number];
